### ISSUE TITLE
Timezone Tune-Up

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wave#11]
Got a report from users on the West Coast that times sometimes are wonky.   Waiting for more info, but started to look at the code to guess what could be going on.   Wild guess at this point is that confusion could be caused by _myquery_ start and end timestamps being interpreted with systemDefault() timezone (America/New_York East Coast) whereas the time series data in the API response used by WAVE for the graphs are UTC UNIX timestamps fed directly into _canvasjs_ as is.   Might want to update WAVE to use the _myquery_ `-a` option to have server local (America/New_York) time applied?  This might be a problem even locally as users likely assume graph data is in JLab timezone, not UTC.

**Comment by baltzell** [comment]
The more specific report I received is that the *time* is reported in the user's local timezone, but the *day* is somehow reported in JLab time zone.  I'll get confirmation and a screenshot from some of our remote shift personell this week.

**Comment by baltzell** [comment]
I tested this with some folks residing in Italy, and we could not reproduce the problem.

**Comment by slominskir** [comment]
Closing for now - we can re-open later if we find problem is reproducible.  Thanks for testing this.

**Comment by slominskir** [comment]
Reopening due to #18.   Poking around looks like modern web browsers may finally be able to take a UTC date and convert it to a representation in an arbitrary timezone now.   But not convert Date object to Date object though, just Date to String.   Hmm.   Anyways something to look into if we want to avoid weird server-side timezone shifting of pseudo-UTC (that apparently isn't setup correctly in this WAVE project - working correctly in other projects though).  See:  https://momentjs.com/docs/#/-project-status/recommendations/

Also, it appears we're currently not instructing canvasjs to NOT do any conversion as intended.  See: https://canvasjs.com/forums/topic/datetime-stamp-time-zone/

**Comment by slominskir** [comment]
https://github.com/JeffersonLab/wave/wiki/Timezone-Notes
