### ISSUE TITLE
Sometimes the y-axis values are overly truncated with insufficient significant figures

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/wave#12]
See attached image with all "0.0" on the y-axis, while the range is really (-0.02,0.02) or so.  Seems to be somewhat reproducible by just setting the axis range to cover only small numbers, but sometimes happens on a previously existing axis when adding a PV, or changing the label for a PV.  One thing could just be an additional option to manually choose the number of significant figures displayed.

![Screen Shot 2022-09-21 at 11 00 40 AM](https://user-images.githubusercontent.com/6279258/191540336-72d3789f-b9c2-4a3a-ab90-be1c1efebe1e.png)

**Comment by baltzell** [comment]
Ah, I noticed that if I run in "Live Plot" mode, this truncation appears to always fix itself on the first automatic update.
![Screen Shot 2022-09-21 at 12 09 59 PM](https://user-images.githubusercontent.com/6279258/191555825-0e742690-65da-4266-b331-b2128c4a46cc.png)

**Comment by slominskir** [comment]
It looks like the y-axis rendering function encountered a hic-up or else may have been accidentally overridden (you can click on a series and set min and max axis values.   Starting with a fresh WAVE window and adding the PV B_DAQ:HEL:60m:29:asycorr and setting the same date range as pictured results in the correct display.

![image](https://user-images.githubusercontent.com/2642119/191570471-009f4ebb-ff35-4a90-ba51-32e71c14ec23.png)


[epicsweb.jlab.org/wave](https://epicsweb.jlab.org/wave/?start=2022-09-18+10%3A48%3A32&end=2022-09-21+10%3A53%3A32&myaDeployment=ops&myaLimit=100000&windowMinutes=30&title=&fullscreen=true&layoutMode=1&viewerMode=1&pv=B_DAQ%3AHEL%3A60m%3A29%3Aasycorr&B_DAQ%3AHEL%3A60m%3A29%3Aasycorrlabel=B_DAQ%3AHEL%3A60m%3A29%3Aasycorr&B_DAQ%3AHEL%3A60m%3A29%3Aasycorrcolor=%23a6cee3&B_DAQ%3AHEL%3A60m%3A29%3AasycorryAxisLabel=&B_DAQ%3AHEL%3A60m%3A29%3AasycorryAxisMin=&B_DAQ%3AHEL%3A60m%3A29%3AasycorryAxisMax=&B_DAQ%3AHEL%3A60m%3A29%3AasycorryAxisLog&B_DAQ%3AHEL%3A60m%3A29%3Aasycorrscaler=)
