### ISSUE TITLE
Feature request - datestamp in plot title

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/wave#13]
It would be great to have a timestamp in the plot title, eg Live Plot Last 500 Minutes Ending Tue 18 Oct 09:01am.

**Comment by slominskir** [comment]
Hi, 
  What's the use case for this?   Perhaps it is so you can take a screenshot for review at a later time? 

WAVE already includes the duration in the title and the end time is implied to be "now", which is constantly updating.   The timestamp would simply reflect wall clock time, which isn't very useful if you're viewing the screen real-time and contrary to the goal of keeping the title as concise as possible (for mobile devices).

<img width="429" alt="Screenshot" src="https://user-images.githubusercontent.com/2642119/196454866-dc8bc179-19ca-4920-a80a-2c0e103a2e9a.png">

[Example](https://epicsweb.jlab.org/wave/?start=2020-05-13+13%3A02%3A52&end=2020-05-13+13%3A07%3A52&myaDeployment=ops&myaLimit=100000&windowMinutes=5&title=&fullscreen=false&layoutMode=1&viewerMode=2&pv=IBC2C21AIMAGuV&IBC2C21AIMAGuVlabel=IBC2C21AIMAGuV&IBC2C21AIMAGuVcolor=%23a6cee3&IBC2C21AIMAGuVyAxisLabel=%C2%B5V&IBC2C21AIMAGuVyAxisMin=&IBC2C21AIMAGuVyAxisMax=&IBC2C21AIMAGuVyAxisLog&IBC2C21AIMAGuVscaler=)

We could probably make an option to do this, but I'm not convinced including the timestamp would be a good default.  A workaround, assuming your use-case of screenshot, is to manually edit the title to include the the timestamp:

<img width="487" alt="Screenshot2" src="https://user-images.githubusercontent.com/2642119/196456254-97e74b7c-078a-4c53-a2d7-76888e96ef63.png">

**Comment by slominskir** [comment]
This request has made me ponder.   Perhaps another possible use-case is to provide some form of feedback that the plot is "working".   This is useful for signals that do not update very frequently.   I've seen a similar strategy on EDM screens (clock timestamps), that are provided by an EPICS PV.  

A naïve implementation that simply applies a clock purely client-side would not provide much guarantee that the plot is working, so some clock updates would need to come from the server if the purpose is a liveness mechanism or rely on the existing liveness mechanism.    The underlying lib epics2web actually does notify on disconnect, but WAVE currently ignores this - disconnecting the device Internet connection on a live plot doesn't currently notify users, and you have to open the developer console on your browser to see WebSocket failure messages.  The chart continues scrolling at the last known value.   Some notification would be nice, though it wouldn't need to be an ever-present clock timestamp.

**Comment by nsjarvis** [comment]
Hi,

Yes, it's because I save the plots for later reference.   Having the time
already on the plot saves me from editing it in powerpoint or preview or
whatever else.
Maybe it could be configurable?

I realise that the fixed-time display already has the time limits included
in the plot title, so I should be able to use that instead, but when I
switch between live and fixed using the sidebar menu, the time period shown
changes.  I think the fixed time interval limits presented greyed out in
the menu might be populated when I first show the live plot?  I'm not sure
what's going on here.

Naomi.

**Comment by slominskir** [comment]
An option for this seems reasonable, or detect if screen is large (desktop-size) and automatically add the timestamp - it likely is only a concern on mobile devices.

It also sounds reasonable to set the fixed range to match the most recent live plot: https://github.com/JeffersonLab/wave/issues/14

**Comment by nsjarvis** [comment]
Making the fixed range match the most recent live plot would be really helpful, it can be confusing when the date range changes.

**Comment by slominskir** [comment]
Now that switching to a fixed plot maintains the live chart bounds it is easy to pause to take a screenshot so I'm closing this: https://github.com/JeffersonLab/wave/issues/14.
