### ISSUE TITLE
Setting the color to #0 makes the axis labels disappear

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/wave#16]
but setting it to #000000 shows them in black as expected.

**Comment by slominskir** [comment]
The series color field in WAVE is a CSS Color field, which means any valid color rule that a web browser takes should work.  The value `#0` is an invalid hex color rule.    A hex color rule requires a minimum of three numbers (for red, green, and blue).   So `#000` works.

See: [Hex Color](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color)
