### ISSUE TITLE
Feature request: choose one PV to bring to the top of a shared chart

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/wave#17]
I use the same chart, separate axis view most often because it creates the largest chart, and I use a laptop.   

Would it be possible to make an option to rearrange the display order of the PVs so that one in particular could be shown on top of the others, please?  I guess drag and drop ordering would be nice, but that seems over the top, I would be really happy if just one could be picked as the plot on top.  

It would be really useful when trying to see a cleaner trace that is hidden beneath a noisy one, [here is an example](https://epicsweb.jlab.org/wave/?myaDeployment=ops&myaLimit=100000&title=&fullscreen=false&layoutMode=3&viewerMode=1&pv=RESET%3Ai%3AGasPanelBarPress1&pv=HD%3Acoda%3Acdc_hv_ai%3Aswitch&pv=CDC%3Ahv%3AA%3A1%3Av0set&pv=HD%3Acoda%3AEventRate&RESET%3Ai%3AGasPanelBarPress1label=RESET%3Ai%3AGasPanelBarPress1&RESET%3Ai%3AGasPanelBarPress1color=%23a6cee3&RESET%3Ai%3AGasPanelBarPress1yAxisLabel=&RESET%3Ai%3AGasPanelBarPress1yAxisMin=&RESET%3Ai%3AGasPanelBarPress1yAxisMax=&RESET%3Ai%3AGasPanelBarPress1scaler=&RESET%3Ai%3AGasPanelBarPress1yAxisLog=&windowMinutes=2400&start=2022-10-25+14%3A30%3A32&end=2022-10-28+23%3A20%3A32&HD%3Acoda%3Acdc_hv_ai%3Aswitchlabel=HD%3Acoda%3Acdc_hv_ai%3Aswitch&HD%3Acoda%3Acdc_hv_ai%3Aswitchcolor=%231f78b4&HD%3Acoda%3Acdc_hv_ai%3AswitchyAxisLabel=&HD%3Acoda%3Acdc_hv_ai%3AswitchyAxisMin=&HD%3Acoda%3Acdc_hv_ai%3AswitchyAxisMax=&HD%3Acoda%3Acdc_hv_ai%3AswitchyAxisLog=&HD%3Acoda%3Acdc_hv_ai%3Aswitchscaler=&CDC%3Ahv%3AA%3A1%3Av0setyAxisLabel=&CDC%3Ahv%3AA%3A1%3Av0setyAxisMin=&CDC%3Ahv%3AA%3A1%3Av0setyAxisMax=&CDC%3Ahv%3AA%3A1%3Av0setyAxisLog&CDC%3Ahv%3AA%3A1%3Av0setscaler=&IBCAD00CRCUR6yAxisLabel=&IBCAD00CRCUR6yAxisMin=&IBCAD00CRCUR6yAxisMax=&IBCAD00CRCUR6yAxisLog=&IBCAD00CRCUR6scaler=&HD%3Acoda%3AEventRateyAxisLabel=&HD%3Acoda%3AEventRateyAxisMin=&HD%3Acoda%3AEventRateyAxisMax=&HD%3Acoda%3AEventRateyAxisLog=&HD%3Acoda%3AEventRatescaler=&HLD%3ATGT%3AstatusyAxisLabel=&HLD%3ATGT%3AstatusyAxisMin=&HLD%3ATGT%3AstatusyAxisMax=&HLD%3ATGT%3AstatusyAxisLog=&HLD%3ATGT%3Astatusscaler=&CDC%3Ahv%3AA%3A1%3Av0setlabel=CDC%3Ahv%3AA%3A1%3Av0set&CDC%3Ahv%3AA%3A1%3Av0setcolor=%23000).

**Comment by slominskir** [comment]
The draw on top order is determined by PV order, with last added PV drawn top-most.   If you're looking to always have the same PV order just be sure to add PVs to the chart with the specific order.   Re-ordering an existing chart can be done by editing the URL as a workaround.  For the example given above the URL parameters in question are:

```
&pv=CDC%3Ahv%3AA%3A1%3Av0set&pv=RESET%3Ai%3AGasPanelBarPress1&pv=HD%3Acoda%3Acdc_hv_ai%3Aswitch&pv=HD%3Acoda%3AEventRate
```

Other existing workarounds include the ability to hide a series, remove a series, or separate them in their own charts.

Drag and Drop would likely be clumsy on a small phone.  A new button in the series properties that moves the series position later in the list seems reasonable.

**Comment by nsjarvis** [comment]
Yes please, that would be great.  The urls get very long, our PV names are not short.

**Comment by nsjarvis** [comment]
Thank you!
