### ISSUE TITLE
Fix flot tooltip plugin to hide tooltip on mouseleave

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wave#2]
Sometimes the tooltip hangs around even when the mouse isn't over the plot area.  This happens if you move the mouse fast.  Mentioned here:

https://github.com/krzysu/flot.tooltip/issues/97

The fix is probably to register a mouseout/mouseleave listener to fade out the tooltip.  See also:

https://stackoverflow.com/questions/44126244/jquery-flot-the-tooltip-will-not-hide-when-i-move-the-mouse-quickly-out-of-plot

**Comment by apcarp** [comment]
I forked the project and updated the source file.  You can access this here - https://github.com/apcarp/flot.tooltip.  I think this should count as complete since the project isn't actively maintained, and I don't want to own it.
