### ISSUE TITLE
Layout issue when adding new PVs

### ISSUE THREAD

**Issue by apcarp** [JeffersonLab/wave#5]
Adding a second PV with the separate chart layout causes a large white space to be place between the PV entry field and the chart display area.

Affects version 1.6.0.

To recreate:
Start with fresh page.  Enter one PV (R123GSET).  Then enter second PV (R122GSET).  Notice large white space above charts.

**Comment by apcarp** [comment]
Looks like the autocomplete window is leaving holding on to the space even after it stops displaying.

**Comment by slominskir** [comment]
Fixed in release https://github.com/JeffersonLab/wave/releases/tag/v1.7.0
