### ISSUE TITLE
Live Chart doesn't apply deadbands

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wave#7]
Observed that the epics2web updates appear to be more frequent (and have higher precision - see https://github.com/JeffersonLab/jmyapi/issues/7) than data from the archiver. I am assuming this is a deadband thing. See attached screenshot (live chart has been running for about 20 minutes with 60 minute window so roughly 40 minutes of archive data):

<img width="746" alt="Screenshot" src="https://user-images.githubusercontent.com/2642119/82478136-76fca300-9a9e-11ea-998d-fb3538c5f7e9.png">

**Comment by slominskir** [comment]
Looks like Mya LivePlot desktop app has same behavior.  Maybe this isn't really an issue then.   See attached screenshot:

<img width="784" alt="Screenshot" src="https://user-images.githubusercontent.com/2642119/82486121-6b16de00-9aaa-11ea-911b-c8fde4430309.png">

**Comment by apcarp** [comment]
I believe dead bands are implemented in a Mya specific way, and not using
the epics dead and field.

I think this is the expected behavior.  I would consider it a bug if a live
plot did not show me the actual data.

**Comment by slominskir** [comment]
Closing as the observed behavior is desired.
